driver:
  name: azurerm

driver_config:
  subscription_id: <%= ENV['AZURE_SUBSCRIPTIONID'] %>
  location: Australia Southeast
  machine_size: Standard_A2

provisioner:
  name: chef_zero
  
platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
  - name: windows2016
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    transport:
      name: winrm

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/default/default.rb

suites:
  - name: default-chef-14-3-37
    require_chef_omnibus: 14.3.37
    run_list:
      - recipe[chef-splunk-windows::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
 